[package]
name = "drm"
description = "Safe, low-level bindings to the Direct Rendering Manager API"
repository = "https://github.com/Smithay/drm-rs"
version = "0.3.1"
license = "MIT"
authors = ["Tyler Slabinski <tslabinski@slabity.net>"]

[dependencies]
drm-sys = "0.0.9"
drm-macros = "0.0.1"
nix = "0.8.1"

[dependencies.error-chain]
version = "0.11.0"
default-features = false
