[package]
name = "drm"
description = "Safe, low-level bindings to the Direct Rendering Manager API"
version = "0.2.3"
license = "MIT"
authors = ["Tyler Slabinski <tslabinski@slabity.net>"]

[dependencies]
drm-sys = "0.0.9"
drm-macros = "0.0.1"
nix = "0.8.1"

[dependencies.error-chain]
version = "0.10.0"
default-features = false
