[package]
name = "drm"
description = "Safe, low-level bindings to the Direct Rendering Manager API"
repository = "https://github.com/Smithay/drm-rs"
version = "0.0.0"
license = "MIT"
authors = ["Tyler Slabinski <tslabinski@slabity.net>"]

[dependencies]
drm-sys = { path = "drm-sys" }
nix = "*"
derive_more = "*"

[dependencies.error-chain]
version = "*"
default-features = false
