[package]
name = "drm"
description = "Safe, low-level bindings to the Direct Rendering Manager API"
repository = "https://github.com/Smithay/drm-rs"
version = "0.0.0"
license = "MIT"
authors = ["Tyler Slabinski <tslabinski@slabity.net>"]

[dependencies]
drm-ffi = { path = "drm-ffi" }
drm-fourcc = "2.0"
nix = "*"
bitflags = "*"

[dev-dependencies]
image = { version = "*", default-features = false, features = ["png"] }
rustyline = "*"

[features]
use_bindgen = ["drm-ffi/use_bindgen"]
