[package]
name = "drm-macros"
description = "Macros for the drm-rs crate"
version = "0.0.1"
authors = ["Tyler Slabinski <tslabinski@slabity.net>"]
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"